### ISSUE TITLE
words that include both katakana and hiragana

### ISSUE THREAD

**Issue by fuddl** [echamudi/japanese-toolkit#58]
Hey, I tried to combine `消しゴム` and `けしゴム` and expected to find only the `け` associated with the `消`. But instead I find this:

![消しゴム/けしゴム](https://user-images.githubusercontent.com/842548/210650105-bb5c571a-8cc5-4718-9a55-0f07ce37a440.png)

is this a bug or am I holding it wrong? 😅

I mean I could check if `w` and `r` make the same sound before printing it.

**Comment by echamudi** [comment]
Hey, try setting the `kanaReading` key inside the config argument to false.

**Comment by fuddl** [comment]
That’s it. Thank you 🙏
